# --- CONFIGURAÇÃO DO BANCO DE DADOS POSTGRESQL NA NUVEM (RENDER) ---
spring.datasource.url=jdbc:postgresql://dpg-d8sb5fkvikkc739fouu0-a.virginia-postgres.render.com/agentia_db_0dzv
spring.datasource.username=agentia_db_0dzv_user
spring.datasource.password=ybWSCBvrQMPUa3IUAixU5vcfpL8oIfD4

# --- CONFIGURAÇÕES DO HIBERNATE / JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Exibe as consultas SQL no terminal para ajudar a debugar durante o desenvolvimento
spring.jpa.show-sql=true

# Configuracao da IA (A chave vira das variaveis de ambiente)
gemini.api.key=${GEMINI_API_KEY}